
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # https://help.github.com/en/actions/reference/development-tools-for-github-actions#set-an-environment-variable-set-env
    - name: Extract Branch Name
      run: echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"
    - name: Set Release Mode (branch == master)
      if: env.BRANCH == 'master'
      run: echo "::set-env name=PUBLISH::true" 
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm run test-bundle
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true

    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      env: # Or as an environment variable
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: env.PUBLISH == 'true'
      # will do verythingbut publish! (we need the bumped version number)
    - run: npx release-it
      if: env.PUBLISH == 'true'
    - run: npm run build-doc&&cp dist-doc/index.html dist-doc/404.html
      if: env.PUBLISH == 'true'
    - run: cat package.json
      if: env.PUBLISH == 'true'
    - name: Deploy Doc
      if: env.PUBLISH == 'true'
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: dist-doc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
